geometry_msgs/Vector3 targetPose #Where the end effector should be moved to. Relative to current sub position
bool gripperState
bool OPEN=False
bool CLOSED=True
---
float64[] joint_poses #angles the joints should be set to to reach that position
bool inReach
#TODO geometry_msgs/Vector3 sub_pos_correction #Offset required from the sub for the arm to be able to reach the target