jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Registry Details
        id: registry_case
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('LOWERCASE_REPO', process.env.GITHUB_REPOSITORY.toLowerCase())

      - name: Build and Test in Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ env.LOWERCASE_REPO }}/devcontainer
          push: filter
          cacheFrom: ghcr.io/${{ env.LOWERCASE_REPO }}/devcontainer
          
          runCmd: |
            source /opt/ros/jazzy/setup.bash
            
            sudo chown -R $(whoami) .
            rosdep update
            
            rosdep install --from-paths . --ignore-src -y --rosdistro jazzy --skip-keys 'pcl xacro'
            find . -type d -name stonefish_vendor -exec touch {}/COLCON_IGNORE \;

            echo "Building workspace..."
            colcon build --symlink-install

            colcon test